/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('antdv-next')['Button']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADivider: typeof import('antdv-next')['Divider']
    ADrawer: typeof import('antdv-next')['Drawer']
    AInput: typeof import('antdv-next')['Input']
    AInputNumber: typeof import('antdv-next')['InputNumber']
    AModal: typeof import('antdv-next')['Modal']
    APopconfirm: typeof import('antdv-next')['Popconfirm']
    APopover: typeof import('antdv-next')['Popover']
    AProgress: typeof import('antdv-next')['Progress']
    ARangePicker: typeof import('antdv-next')['DateRangePicker']
    ARow: typeof import('antdv-next')['Row']
    ASelect: typeof import('antdv-next')['Select']
    ASlider: typeof import('antdv-next')['Slider']
    ASwitch: typeof import('antdv-next')['Switch']
    ATable: typeof import('antdv-next')['Table']
    ATag: typeof import('antdv-next')['Tag']
    ATree: typeof import('antdv-next')['Tree']
    Badge: typeof import('./src/components/chat/badge.vue')['default']
    Bubble: typeof import('./src/components/chat/bubble.vue')['default']
    Detail: typeof import('./src/components/user/detail.vue')['default']
    Export: typeof import('./src/components/chat/export.vue')['default']
    Header: typeof import('./src/components/chat/header.vue')['default']
    History: typeof import('./src/components/chat/history.vue')['default']
    Input: typeof import('./src/components/chat/input.vue')['default']
    IntentionStack: typeof import('./src/components/chat/intention/stack.vue')['default']
    List: typeof import('./src/components/table/list.vue')['default']
    Main: typeof import('./src/components/contact/main.vue')['default']
    PlanSummary: typeof import('./src/components/admin/plan-summary.vue')['default']
    Processes: typeof import('./src/components/chat/processes.vue')['default']
    Range: typeof import('./src/components/inputs/range.vue')['default']
    RankedList: typeof import('./src/components/admin/ranked-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/table/search.vue')['default']
    SessionItem: typeof import('./src/components/chat/session-item.vue')['default']
    Settings: typeof import('./src/components/chat/settings.vue')['default']
    Signin: typeof import('./src/components/auth/signin.vue')['default']
    Stack: typeof import('./src/components/intention/stack.vue')['default']
    Tabs: typeof import('./src/components/admin/tabs.vue')['default']
    Welcome: typeof import('./src/components/chat/welcome.vue')['default']
  }
}
