/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    Badge: typeof import('./src/components/chat/badge.vue')['default']
    Bubble: typeof import('./src/components/chat/bubble.vue')['default']
    Detail: typeof import('./src/components/user/detail.vue')['default']
    Export: typeof import('./src/components/chat/export.vue')['default']
    Header: typeof import('./src/components/chat/header.vue')['default']
    History: typeof import('./src/components/chat/history.vue')['default']
    Input: typeof import('./src/components/chat/input.vue')['default']
    List: typeof import('./src/components/table/list.vue')['default']
    Main: typeof import('./src/components/contact/main.vue')['default']
    PlanSummary: typeof import('./src/components/admin/plan-summary.vue')['default']
    Processes: typeof import('./src/components/chat/processes.vue')['default']
    Range: typeof import('./src/components/inputs/range.vue')['default']
    RankedList: typeof import('./src/components/admin/ranked-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/table/search.vue')['default']
    SessionItem: typeof import('./src/components/chat/session-item.vue')['default']
    Settings: typeof import('./src/components/chat/settings.vue')['default']
    Signin: typeof import('./src/components/auth/signin.vue')['default']
    Tabs: typeof import('./src/components/admin/tabs.vue')['default']
    Welcome: typeof import('./src/components/chat/welcome.vue')['default']
  }
}
