/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    Badge: typeof import('./src/components/chat/badge.vue')['default']
    Bubble: typeof import('./src/components/chat/bubble.vue')['default']
    Detail: typeof import('./src/components/user/detail.vue')['default']
    Export: typeof import('./src/components/chat/export.vue')['default']
    Header: typeof import('./src/components/chat/header.vue')['default']
    History: typeof import('./src/components/chat/history.vue')['default']
    Input: typeof import('./src/components/chat/input.vue')['default']
    Main: typeof import('./src/components/contact/main.vue')['default']
    Processes: typeof import('./src/components/chat/processes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionItem: typeof import('./src/components/chat/session-item.vue')['default']
    Settings: typeof import('./src/components/chat/settings.vue')['default']
    Signin: typeof import('./src/components/auth/signin.vue')['default']
    Welcome: typeof import('./src/components/chat/welcome.vue')['default']
  }
}
