# Generated by Django 6.0.6 on 2026-06-19 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0001_initial"),
	]

	operations = [
		migrations.CreateModel(
			name="MChatSession",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("username", models.CharField(db_index=True, max_length=150)),
				("title", models.CharField(blank=True, max_length=200)),
				("language", models.CharField(default="es", max_length=10)),
				("n8n_state", models.JSONField(blank=True, null=True)),
				("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
				("updated_on", models.DateTimeField(auto_now=True)),
				(
					"org",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="chat_sessions",
						to="drf_api.morganization",
					),
				),
			],
			options={
				"ordering": ["-updated_on"],
			},
		),
		migrations.CreateModel(
			name="MChatMessage",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("type", models.CharField(max_length=20)),
				("text", models.TextField()),
				("extra", models.JSONField(blank=True, null=True)),
				("timestamp", models.DateTimeField(db_index=True)),
				(
					"session",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="messages",
						to="drf_api.mchatsession",
					),
				),
			],
			options={
				"ordering": ["timestamp"],
			},
		),
	]
