# Generated by Django 6.0.6 on 2026-07-18 13:07

import drf_api.models.organization
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0002_mchatsession_mchatmessage"),
	]

	operations = [
		migrations.AlterField(
			model_name="morganization",
			name="slug",
			field=models.CharField(
				db_index=True,
				max_length=40,
				unique=True,
				validators=[drf_api.models.organization._validate_slug_not_reserved],
			),
		),
	]
