# Generated by Django 6.0.6 on 2026-07-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0003_alter_morganization_slug"),
	]

	operations = [
		migrations.AddField(
			model_name="mchatsession",
			name="connection_key",
			field=models.CharField(blank=True, default="", max_length=150),
		),
		migrations.AddIndex(
			model_name="mchatsession",
			index=models.Index(
				fields=["org", "username", "connection_key"],
				name="drf_api_mch_org_id_7c5940_idx",
			),
		),
	]
