# Generated by Django 6.0.6 on 2026-07-18 17:43

import django.db.models.deletion
import drf_api.models.fields.encrypted_json
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0004_mchatsession_connection_key"),
	]

	operations = [
		migrations.CreateModel(
			name="MB1SSession",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("username", models.CharField(db_index=True, max_length=150)),
				("connection_key", models.CharField(max_length=150)),
				("token", models.CharField(db_index=True, max_length=64, unique=True)),
				(
					"credentials",
					drf_api.models.fields.encrypted_json.EncryptedJSONField(
						default=dict
					),
				),
				("issued_on", models.DateTimeField(auto_now_add=True)),
				("last_active_on", models.DateTimeField(auto_now=True)),
				("expires_at", models.DateTimeField(db_index=True)),
				(
					"org",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="b1s_sessions",
						to="drf_api.morganization",
					),
				),
			],
			options={
				"indexes": [
					models.Index(
						fields=["org", "username", "connection_key"],
						name="drf_api_mb1_org_id_a0eba7_idx",
					)
				],
			},
		),
	]
