# Generated by Django 6.0.6 on 2026-07-18 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0005_mb1ssession"),
	]

	operations = [
		migrations.AddField(
			model_name="morganization",
			name="seat_limit",
			field=models.PositiveIntegerField(default=0),
		),
		migrations.CreateModel(
			name="MSeat",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("username", models.CharField(db_index=True, max_length=150)),
				(
					"status",
					models.CharField(
						choices=[("active", "Active"), ("revoked", "Revoked")],
						db_index=True,
						default="active",
						max_length=10,
					),
				),
				("granted_on", models.DateTimeField(auto_now_add=True)),
				("revoked_on", models.DateTimeField(blank=True, null=True)),
				(
					"revoked_by",
					models.CharField(blank=True, default="", max_length=150),
				),
				(
					"org",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="seats",
						to="drf_api.morganization",
					),
				),
			],
			options={
				"constraints": [
					models.UniqueConstraint(
						fields=("org", "username"), name="uniq_seat_org_username"
					)
				],
			},
		),
	]
