# Generated by Django 6.0.6 on 2026-07-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0006_mseat"),
	]

	operations = [
		migrations.CreateModel(
			name="MUsageEvent",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("username", models.CharField(db_index=True, max_length=150)),
				(
					"connection_key",
					models.CharField(blank=True, default="", max_length=150),
				),
				(
					"event_type",
					models.CharField(
						choices=[
							("token_usage", "Token Usage"),
							("process_execution", "Process Execution"),
						],
						db_index=True,
						max_length=20,
					),
				),
				("occurred_on", models.DateTimeField(db_index=True)),
				(
					"process_name",
					models.CharField(blank=True, default="", max_length=150),
				),
				(
					"model_name",
					models.CharField(blank=True, default="", max_length=100),
				),
				("prompt_tokens", models.PositiveIntegerField(blank=True, null=True)),
				(
					"completion_tokens",
					models.PositiveIntegerField(blank=True, null=True),
				),
				("total_tokens", models.PositiveIntegerField(blank=True, null=True)),
				(
					"org",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="usage_events",
						to="drf_api.morganization",
					),
				),
				(
					"session",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="usage_events",
						to="drf_api.mchatsession",
					),
				),
			],
			options={
				"indexes": [
					models.Index(
						fields=["org", "event_type", "occurred_on"],
						name="drf_api_mus_org_id_ff6769_idx",
					),
					models.Index(
						fields=["org", "username", "event_type"],
						name="drf_api_mus_org_id_d5aeaf_idx",
					),
				],
			},
		),
	]
