# Generated by Django 6.0.6 on 2026-07-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0007_musageevent"),
	]

	operations = [
		migrations.RenameModel(
			old_name="MB1SSession",
			new_name="MSessionProxy",
		),
		migrations.RenameIndex(
			model_name="msessionproxy",
			new_name="session_proxy_org_user_key_idx",
			old_name="drf_api_mb1_org_id_a0eba7_idx",
		),
		migrations.AddField(
			model_name="msessionproxy",
			name="auth_driver",
			field=models.CharField(db_index=True, default="b1s", max_length=20),
			preserve_default=False,
		),
		migrations.AlterField(
			model_name="msessionproxy",
			name="org",
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="session_proxies",
				to="drf_api.morganization",
			),
		),
	]
