# Generated by Django 6.0.6 on 2026-07-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0008_rename_mb1ssession_msessionproxy_and_more"),
	]

	operations = [
		migrations.AddField(
			model_name="morganization",
			name="plan",
			field=models.JSONField(blank=True, default=dict),
		),
	]
