# Generated by Django 6.0.7 on 2026-08-01 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0009_morganization_plan"),
	]

	operations = [
		migrations.CreateModel(
			name="MBucketFile",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("name", models.CharField(max_length=255)),
				(
					"origin",
					models.CharField(
						choices=[
							("user_upload", "User Upload"),
							("workflow_generated", "Workflow Generated"),
						],
						default="user_upload",
						max_length=20,
					),
				),
				("mime_type", models.CharField(blank=True, default="", max_length=100)),
				("size", models.PositiveIntegerField(default=0)),
				(
					"storage_path",
					models.CharField(blank=True, default="", max_length=500),
				),
				(
					"description",
					models.CharField(blank=True, default="", max_length=255),
				),
				("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
				(
					"session",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="bucket_files",
						to="drf_api.mchatsession",
					),
				),
			],
			options={
				"ordering": ["-created_on"],
			},
		),
	]
