# Generated by Django 6.0.7 on 2026-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0010_mbucketfile"),
	]

	operations = [
		migrations.AddField(
			model_name="mbucketfile",
			name="extracted_content",
			field=models.TextField(blank=True, default=None, null=True),
		),
	]
