# Generated by Django 6.0.7 on 2026-08-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0011_mbucketfile_extracted_content"),
	]

	operations = [
		migrations.RemoveField(
			model_name="mchatsession",
			name="language",
		),
	]
