# Generated by Django 6.1 on 2026-08-21 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0012_remove_language_fields"),
	]

	operations = [
		migrations.CreateModel(
			name="MDocumentTemplate",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("document_type", models.CharField(max_length=50)),
				("name", models.CharField(max_length=255)),
				("is_default", models.BooleanField(default=False)),
				(
					"original_filename",
					models.CharField(blank=True, default="", max_length=255),
				),
				(
					"storage_path",
					models.CharField(blank=True, default="", max_length=500),
				),
				("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
				("updated_on", models.DateTimeField(auto_now=True)),
				(
					"org",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="document_templates",
						to="drf_api.morganization",
					),
				),
			],
			options={
				"ordering": ["-created_on"],
			},
		),
	]
