# Generated by Django 6.1 on 2026-08-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0013_mdocumenttemplate"),
	]

	operations = [
		migrations.AddField(
			model_name="mdocumenttemplate",
			name="business_partner_ref",
			field=models.CharField(blank=True, default="", max_length=50),
		),
		migrations.AddField(
			model_name="mdocumenttemplate",
			name="language",
			field=models.CharField(blank=True, default="", max_length=10),
		),
	]
