# Generated by Django 6.1.1 on 2026-09-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0014_mdocumenttemplate_business_partner_ref_and_more"),
	]

	operations = [
		migrations.AddField(
			model_name="mchatsession",
			name="deleted_on",
			field=models.DateTimeField(blank=True, db_index=True, null=True),
		),
	]
