# Generated by Django 6.1.1 on 2026-09-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0015_mchatsession_deleted_on"),
	]

	operations = [
		migrations.AddField(
			model_name="morganization",
			name="company_info",
			field=models.JSONField(blank=True, default=dict),
		),
	]
