# Generated by Django 6.1.1 on 2026-09-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0016_morganization_company_info"),
	]

	operations = [
		migrations.CreateModel(
			name="MProject",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				(
					"deleted_on",
					models.DateTimeField(blank=True, db_index=True, null=True),
				),
				(
					"accessed_on",
					models.DateTimeField(auto_now_add=True, db_index=True),
				),
				(
					"connection_key",
					models.CharField(blank=True, default="", max_length=150),
				),
				("created_on", models.DateTimeField(auto_now_add=True)),
				("is_default", models.BooleanField(default=False)),
				("name", models.CharField(max_length=200)),
				("summary", models.TextField(blank=True, default="")),
				("updated_on", models.DateTimeField(auto_now=True)),
				("username", models.CharField(db_index=True, max_length=150)),
				(
					"org",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="projects",
						to="drf_api.morganization",
					),
				),
			],
			options={
				"ordering": ["-accessed_on"],
				"indexes": [
					models.Index(
						fields=["org", "username", "connection_key"],
						name="drf_api_mpr_org_id_f3efd7_idx",
					)
				],
				"constraints": [
					models.UniqueConstraint(
						condition=models.Q(("is_default", True)),
						fields=("org", "username", "connection_key"),
						name="unique_default_project_per_identity",
					)
				],
			},
		),
	]
