# Generated by Django 6.1.1 on 2026-09-25 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0017_mproject"),
	]

	operations = [
		# Nullable on purpose: existing rows have no project yet, 0019 backfills them and
		# 0020 tightens this to NOT NULL.
		migrations.AddField(
			model_name="mchatsession",
			name="project",
			field=models.ForeignKey(
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				related_name="chat_sessions",
				to="drf_api.mproject",
			),
		),
	]
