# Generated by Django 6.1.1 on 2026-09-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("drf_api", "0019_backfill_default_projects"),
	]

	operations = [
		# Fails outright (no data corruption) if any chat session still has no project, e.g.
		# one created by old app code between 0019 and this step during a rolling deploy.
		migrations.AlterField(
			model_name="mchatsession",
			name="project",
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="chat_sessions",
				to="drf_api.mproject",
			),
		),
	]
