"""Django settings for core project."""
# Generated by "django-admin startproject" using Django 5.1.
# https://docs.djangoproject.com/en/5.1/topics/settings/
# https://docs.djangoproject.com/en/5.1/ref/settings/

# General imports
import os
from pathlib import Path

# Libs imports
from corsheaders.defaults import default_headers

# App imports
from core.modules.configuration import Configuration

# Initialize Configuration
CONFIG = Configuration().get()

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = CONFIG.get("SECRET_KEY", "")

FIELD_ENCRYPTION_KEY = CONFIG.get("FIELD_ENCRYPTION_KEY", "")


# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = CONFIG.get("MODE") == "dev"

ALLOWED_HOSTS = CONFIG.get("ALLOWED_HOSTS").split(" ") or []

# Application definition
INSTALLED_APPS = [
	"django.contrib.admin",
	"django.contrib.auth",
	"django.contrib.contenttypes",
	"django.contrib.sessions",
	"django.contrib.messages",
	"django.contrib.staticfiles",
	# third party
	"channels",
	"corsheaders",
	"django_filters",
	"drf_standardized_errors",
	"rest_framework",
	# apps
	"core",
	"drf_api",
]

MIDDLEWARE = [
	"corsheaders.middleware.CorsMiddleware",
	"django.middleware.security.SecurityMiddleware",
	"django.contrib.sessions.middleware.SessionMiddleware",
	"django.middleware.common.CommonMiddleware",
	"django.middleware.csrf.CsrfViewMiddleware",
	"django.contrib.auth.middleware.AuthenticationMiddleware",
	"django.contrib.messages.middleware.MessageMiddleware",
	"django.middleware.clickjacking.XFrameOptionsMiddleware",
	"drf_api.middleware.organization.MOrganizationMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
	{
		"BACKEND": "django.template.backends.django.DjangoTemplates",
		"DIRS": [
			os.path.join(BASE_DIR, "core", "templates", "emails"),
		],
		"APP_DIRS": True,
		"OPTIONS": {
			"context_processors": [
				"django.template.context_processors.debug",
				"django.template.context_processors.request",
				"django.contrib.auth.context_processors.auth",
				"django.contrib.messages.context_processors.messages",
			],
		},
	},
]

ASGI_APPLICATION = "core.asgi.application"
WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
	"default": {
		# "django.db.backends.sqlite3" or "core.driver.aws_aurora",
		"ENGINE": CONFIG.get("DB_ENGINE"),
		"NAME": CONFIG.get("DB_NAME"),
	}
}
if CONFIG.get("DB_HOST"):
	DATABASES["default"]["HOST"] = CONFIG.get("DB_HOST")
	db_ssl_mode = CONFIG.get("DB_SSL_MODE", "require")
	if db_ssl_mode:
		DATABASES["default"]["OPTIONS"] = {"sslmode": db_ssl_mode}
	DATABASES["default"]["PASSWORD"] = CONFIG.get("DB_PASSWORD")
	DATABASES["default"]["PORT"] = CONFIG.get("DB_PORT", "5432")
	DATABASES["default"]["USER"] = CONFIG.get("DB_USER")


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
	},
	{"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
	{"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
	{"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
	{"NAME": "core.validators.password.VNonAlphanumericPassword"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "static/"
STATICFILES_DIRS = (os.path.join(BASE_DIR, "media"),)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# DRF Settings
REST_FRAMEWORK = {
	"DEFAULT_AUTHENTICATION_CLASSES": (
		"rest_framework.authentication.SessionAuthentication",
	),
	"DEFAULT_FILTER_BACKENDS": [
		"django_filters.rest_framework.DjangoFilterBackend",
		# "rest_framework.filters.OrderingFilter",
	],
	"DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
	"DEFAULT_PARSER_CLASSES": ("rest_framework.parsers.JSONParser",),
	"DEFAULT_PERMISSION_CLASSES": (),
	"DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.NamespaceVersioning",
	"DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
	"EXCEPTION_HANDLER": "core.handler.exceptions.exception_handler",
	"PAGE_SIZE": 10,
}

CORS_ALLOW_HEADERS = list(default_headers) + ["x-sap-connection-key", "x-sap-username"]

if DEBUG:
	CORS_ALLOW_CREDENTIALS = True
	CORS_ALLOW_ALL_ORIGINS = True
	# Allow local dev origins to pass Django's CSRF Origin check (Django 4.0+).
	# Subdomains (org slugs) use *.blas.local; Vite dev server runs on :5173.
	CSRF_TRUSTED_ORIGINS = [
		"http://*.blas.local:5173",
		"http://*.blas.local:8000",
		"http://localhost:5173",
		"http://127.0.0.1:5173",
	]
else:
	# CSRF and Secure session
	CSRF_COOKIE_SECURE = True
	# ALLOWED_HOSTS may use Django's leading-dot wildcard syntax (e.g. ".orb.darchsystems.com")
	# to match a bare domain plus every tenant subdomain. CSRF_TRUSTED_ORIGINS has its own,
	# different wildcard syntax (leading "*."), so a leading dot must be translated rather
	# than copied verbatim — otherwise tenant-subdomain requests fail CSRF checks in production.
	CSRF_TRUSTED_ORIGINS = [
		f"https://*{domain}" if domain.startswith(".") else f"https://{domain}"
		for domain in ALLOWED_HOSTS
	]
	SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
	SESSION_COOKIE_SECURE = True
	USE_X_FORWARDED_HOST = True

# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_FROM = CONFIG.get("EMAIL_FROM")
EMAIL_HOST = CONFIG.get("EMAIL_HOST")
EMAIL_HOST_PASSWORD = CONFIG.get("EMAIL_HOST_PASSWORD")
EMAIL_HOST_USER = CONFIG.get("EMAIL_HOST_USER")
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Async task settings
BROKER_URL = CONFIG.get("BROKER_URL")

FILE_UPLOAD_HANDLERS = [
	"django.core.files.uploadhandler.TemporaryFileUploadHandler",
]

N8N_CALLBACK_SECRET = CONFIG.get("N8N_CALLBACK_SECRET", "")

# Object storage — driver selected by STORAGE_DRIVER (see core/modules/storage/driver/),
# same pluggable-driver pattern as CFG_DRIVER/core/modules/configuration/driver/.
# "aws_s3" (prod) talks to real AWS S3; "minio" (dev) extends it, only overriding the
# client to point at STORAGE_ENDPOINT_URL, which "aws_s3" itself never reads.
STORAGE_DRIVER = CONFIG.get("STORAGE_DRIVER", "aws_s3")
STORAGE_ACCESS_KEY = CONFIG.get("STORAGE_ACCESS_KEY", "")
STORAGE_BUCKET_NAME = CONFIG.get("STORAGE_BUCKET_NAME", "")
STORAGE_ENDPOINT_URL = CONFIG.get("STORAGE_ENDPOINT_URL", "")
STORAGE_REGION = CONFIG.get("STORAGE_REGION", "us-east-1")
STORAGE_SECRET_KEY = CONFIG.get("STORAGE_SECRET_KEY", "")
BUCKET_MAX_FILE_SIZE_MB = int(CONFIG.get("BUCKET_MAX_FILE_SIZE_MB", 25))
BUCKET_MAX_BATCH_SIZE_MB = int(CONFIG.get("BUCKET_MAX_BATCH_SIZE_MB", 20))

# Redis — shared by CHANNEL_LAYERS below and the n8n helpers (web_socket/helpers/n8n/),
# which read these as settings.REDIS_HOST/REDIS_PORT rather than settings.CONFIG directly.
REDIS_HOST = CONFIG.get("REDIS_HOST", "localhost")
REDIS_PORT = int(CONFIG.get("REDIS_PORT", 6379))

# n8n helper TTLs (web_socket/helpers/n8n/queue.py, state.py)
N8N_INFLIGHT_TTL_SECONDS = int(CONFIG.get("N8N_INFLIGHT_TTL_SECONDS", 300))
FORM_STATE_TTL_SECONDS = int(CONFIG.get("FORM_STATE_TTL_SECONDS", 86400))

# Channel settings
CHANNEL_LAYERS = {
	"default": {
		"BACKEND": "channels_redis.core.RedisChannelLayer",
		"CONFIG": {
			"hosts": [
				{
					"host": REDIS_HOST,
					"port": REDIS_PORT,
					"retry_on_timeout": True,
					"socket_connect_timeout": 10,
					"socket_timeout": None,
				}
			],
		},
	},
}

# Logging
LOGGING = {
	"version": 1,
	"disable_existing_loggers": False,
	"handlers": {
		"null": {
			"class": "logging.NullHandler",
		},
		"console": {
			"class": "logging.StreamHandler",
		},
	},
	"root": {
		"handlers": ["console"],
		"level": "INFO",
	},
	"loggers": {
		"django": {
			"handlers": ["console"],
			"level": "INFO",
			"propagate": False,
		},
		"django.request": {
			"handlers": ["console"],
			"level": "ERROR",
			"propagate": False,
		},
		"django.security.DisallowedHost": {
			"handlers": ["null"],
			"propagate": False,
		},
	},
}
